<a href="https://colab.research.google.com/github/anushzz/compute_tasks/blob/main/task_2/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Import NumPy

In [ ]:
pip install numpy

In [ ]:
import numpy as np

#### Create an array of 10 zeros

In [ ]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
arr2=np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [ ]:
arr3=np.full(10,5,dtype=float)
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50 -!del!-

In [ ]:
arr4=np.arange(10,51)
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50  -!del!-

In [ ]:
arr5=np.arange(10,51,2)
arr5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr6=np.arange(9).reshape(3,3)
arr6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
arr7=np.identity(3)
arr7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1  -!del!-

In [ ]:
rno=np.random.rand(1)
rno

array([0.12700829])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
#Normal distribution is mean=0 SD=1

arr8=np.random.randn(25)
arr8

array([-0.91334282,  0.22382925, -0.87952104,  0.03738322,  0.14271712,
       -0.14989169, -0.69101766, -1.08548224,  1.26200083,  0.53145196,
        0.02727715,  1.43407178,  1.54587201, -1.1940715 , -0.32867614,
        0.2091685 ,  1.65629654, -0.06884416,  1.93625089,  1.22427297,
       -0.3313142 ,  2.18031404,  1.56620934,  0.79622316,  1.37299606])

#### Create the following matrix: -!del!-

In [ ]:
arr9=np.arange(0.01,1.01,0.01).reshape(10,10)
arr9

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
arr10=np.linspace(0,1,20)
arr10

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat1=mat[2:,1:]
mat1

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
ele=mat[3][4]
ele

20

In [ ]:
mat2=mat[0:3,1:2]
mat2

array([[ 2],
       [ 7],
       [12]])

In [ ]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
sum=np.sum(mat)
sum

325

#### Get the standard deviation of the values in mat

In [ ]:
sd=np.std(mat)
sd

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
col_sum=np.sum(mat, axis=0)
col_sum

array([55, 60, 65, 70, 75])

#### Multiply two matrices using NumPy.

A = [[1, 2], [2, 3]]

B = [[4, 5], [6, 7]]

So, A.B = [[1*4 + 2*6, 2*4 + 3*6], [1*5 + 2*7, 2*5 + 3*7]

The computed answer will be: [[16, 26], [19, 31]]


In [ ]:
A = [[1, 2], [2, 3]]
B = [[4, 5], [6, 7]]
mul=np.dot(A,B)
mul

array([[16, 19],
       [26, 31]])

####Replace NaN values with average of that column

Initial array :  

[[ 1.3  2.5  3.6  nan]
 [ 2.6  3.3  nan  5.5]
 [ 2.1  3.2  5.4  6.5]]


In [ ]:
a = np.array([[1.3, 2.5, 3.6, np.nan],[2.6, 3.3, np.nan, 5.5],[2.1, 3.2, 5.4, 6.5]])
mean=np.nanmean(a,axis=0)
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if np.isnan(a[i][j]):
            a[i][j] = mean[j]
a


array([[1.3, 2.5, 3.6, 6. ],
       [2.6, 3.3, 4.5, 5.5],
       [2.1, 3.2, 5.4, 6.5]])

# You're done!